linters:
  enable-all: true
  disable:
    - depguard  # not currently used
    - execinquery  # archived by the owner
    - exportloopref  # replaced by 'copyloopvar'
    - gomnd  # replaced by 'mnd'

linters-settings:
  misspell:
    locale: US
