version: '3.8'

services:
  whoami:
    image: traefik/whoami:v1.9.0
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.http.routers.whoami.entryPoints: default
        traefik.http.routers.whoami.middlewares: any-auth@docker
        traefik.http.routers.whoami.rule: PathPrefix(`/whoami`)
        traefik.http.services.whoami.loadbalancer.server.port: 80
  whoami-cl1:
    image: traefik/whoami:v1.9.0
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.http.routers.whoami-cl1.entryPoints: default
        traefik.http.routers.whoami-cl1.middlewares: cl1-auth@docker
        traefik.http.routers.whoami-cl1.rule: PathPrefix(`/whoami-cl1`)
        traefik.http.services.whoami-cl1.loadbalancer.server.port: 80
  whoami-cl12:
    image: traefik/whoami:v1.9.0
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.http.routers.whoami-cl12.entryPoints: default
        traefik.http.routers.whoami-cl12.middlewares: cl12-auth@docker
        traefik.http.routers.whoami-cl12.rule: PathPrefix(`/whoami-cl12`)
        traefik.http.services.whoami-cl12.loadbalancer.server.port: 80

networks:
  default:
    external: true
    name: traefik_services
