version: '3.8'

services:
  dsproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    environment:
      LOG_LEVEL: notice
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  fwdauth:
    image: ghcr.io/hhromic/traefik-fwdauth:v2.1.0
    environment:
      OIDC_ISSUER_URL: https://my-oidc-provider
      CLIENT_ID: my-client-id
      CLIENT_SECRET_FILE: /run/secrets/client-secret
      EXPIRE_AFTER: 60s
    secrets:
      - client-secret
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      labels:
        traefik.enable: 'true'
        # any-auth: any issuer client ID is accepted
        traefik.http.middlewares.any-auth.forwardauth.address:
          http://fwdauth:4181/auth?token_type_hint=access_token
        traefik.http.middlewares.any-auth.forwardauth.authResponseHeaders:
          X-Forwarded-Client-Id, X-Forwarded-Scope, X-Forwarded-Subject
        # cl1-auth: only tokens issued by 'client1' are accepted
        traefik.http.middlewares.cl1-auth.forwardauth.address:
          http://fwdauth:4181/auth?client_id=client1&token_type_hint=access_token
        traefik.http.middlewares.cl1-auth.forwardauth.authResponseHeaders:
          X-Forwarded-Client-Id, X-Forwarded-Scope, X-Forwarded-Subject
        # cl12-auth: only tokens issued by 'client1' or 'client2' are accepted
        traefik.http.middlewares.cl12-auth.forwardauth.address:
          http://fwdauth:4181/auth?client_id=client1&client_id=client2&token_type_hint=access_token
        traefik.http.middlewares.cl12-auth.forwardauth.authResponseHeaders:
          X-Forwarded-Client-Id, X-Forwarded-Scope, X-Forwarded-Subject
        traefik.http.services.fwdauth.loadbalancer.server.port: 4181
  traefik:
    image: traefik:v2.10.3
    environment:
      TRAEFIK_ACCESSLOG: 'true'
      TRAEFIK_ACCESSLOG_FILEPATH: /dev/stderr
      TRAEFIK_ACCESSLOG_FORMAT: json
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_USER-AGENT: keep
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_X-FORWARDED-CLIENT-ID: keep
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_X-FORWARDED-SCOPE: keep
      TRAEFIK_ACCESSLOG_FIELDS_HEADERS_NAMES_X-FORWARDED-SUBJECT: keep
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_DEFAULT_ADDRESS: ':5555'
      TRAEFIK_GLOBAL_CHECKNEWVERSION: 'false'
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: 'false'
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: http://dsproxy:2375
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER_SWARMMODE: 'true'
    ports:
      - mode: host
        published: 5555
        target: 5555
      - mode: host
        published: 8080
        target: 8080
    networks:
      - default
      - services
    deploy:
      endpoint_mode: dnsrr
      mode: global

secrets:
  client-secret:
    external: true
    name: client-secret

networks:
  default: {}
  services: {}
